### ISSUE TITLE
tolerance argument in get_most_probable_strand_consensus() function

### ISSUE THREAD

**Issue by PierreL-B** [sequana/sequana_rnaseq#5]
Hi,
I think there is an error in rnasq.rules, line 439:
"probable_strand = fc.get_most_probable_strand_consensus(".", tolerance=tolerance)"
The get_most_probable_strand_consensus() function in featurescount package does not have any tolerance argument.
It's the get_most_probable_strand() function that does.
The pipeline thus throws me an error, as tolerance is an unknown argument.

Should I remove it in the rnaseq.rules file ?

Thanks,
Pierre

**Comment by cokelaer** [comment]
Fixed in version 0.9.18
